version: '3.8'

services:
  mobilefacenet-service:
    build: .
    container_name: mobilefacenet-service
    ports:
      - "5002:5002"
    volumes:
      - ./models_data:/app/models_data
      - ./logs:/app/logs
    environment:
      - MODEL_NAME=buffalo_l
      - VERIFICATION_THRESHOLD=0.70
      - HOST=0.0.0.0
      - PORT=5002
      - PROVIDERS=["CPUExecutionProvider"]
    restart: unless-stopped